image: docker

# 缓存
cache:
  key: npm-cache
  paths:
    - /home/gitlab-runner/npm-cache

# 构建步骤
stages:
  - package
  - build
  - release
  - deploy

# 使用npm打包
npm-package:
  tags:
    - dev
    - test
    - master
  image: node:15.4.0
  stage: package
  only:
    - dev
    - test
    - master
  script:
    - yarn install --legacy-peer-deps --cache-folder=/home/gitlab-runner/npm-cache
    - yarn run build
  artifacts:
    paths:
      - dist
      - docker

# 构建docker镜像
docker-build:
  tags:
    - dev
    - test
  stage: build
  dependencies:
    - npm-package
  only:
    - dev
    - test
    - master
  script:
    - docker build -f docker/Dockerfile -t ngnix/app:v1.0.0 .
    - if [ $(docker ps -aq --filter name=myfellas_admin_web) ]; then docker rm -f myfellas_admin_web;fi
    - docker run -p 8004:80 --name myfellas_admin_web -d ngnix/app:v1.0.0
    - pwd && ls
    - docker build -f docker/Dockerfile -t harbor.vianstats.com/myfellas/myfellas-admin-web .
    - docker login --username=viangz harbor.vianstats.com -p Viangz12
    - docker push harbor.vianstats.com/myfellas/myfellas-admin-web

# dev分支尝试从k8s启动
k8s-run:
  tags:
    - dev
  image: cnych/kubectl
  stage: deploy
  only:
    - dev
  script:
    - kubectl apply -f docker/Deployment.yaml