export default {
  RESET_STATE: 'RESET_STATE',
  SET_MENU: 'SET_MENU',
  RESET_MENU: 'RESET_MENU',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_PHONE_VCODE_SECONDS: 'SET_PHONE_VCODE_SECONDS',
  SET_EMAIL_VCODE_SECONDS: 'SET_EMAIL_VCODE_SECONDS',
}