export default {
  test: '/11/test',
  studentRegister: "/user/register/email",
  adminRegister: "/admin/register/email",
  schoolLogin: '/user/login/account/school',
  studentLogin: "/user/login/email",
  consultantLogin: "/admin/login/email",
  adminLogin: "/admin/login/account",
  logout: "/user/logout",
  adminLogout: "/admin/logout",
  userinfo: "/user/info",
  admininfo: "/admin/adminUser/info",
  schoolEmailChange: '/admin/userAdmin/account/bindEmail/verify',
  schoolEmailBind: '/admin/userAdmin/account/bindEmail',
  studentEmailVerify: "/user/register/email/code",
  adminEmailVerify: "/admin/email/code",
  forgetAndResetPassword: '/user/register/password/forget/reset',
  adminForgetAndResetPassword: '/admin/adminUser/account/password/forget/reset',
  contactAdmin: '/user/register/password/forget/concat',
  getMessages: '',
  avatarUpload: '/oss/minio/putObjectTest',
  editAdminPersonalBase: '/admin/adminUser/info',
  resetStudentPassword: '/user/register/password/reset',
  resetAdminPassword: '/admin/adminUser/account/password',
  resetSchoolPassword: '/admin/userAdmin/account/password',
}