export default {
  test: '/11/test',
  studentRegister: "/user/register/email",
  adminRegister: "/admin/register/email",
  schoolLogin: '/user/login/account/school',
  studentLogin: "/user/login/email",
  adminLogin: "/admin/login/account",
  logout: "/user/logout",
  adminLogout: "/admin/logout",
  userinfo: "/user/info",
  admininfo: "/admin/info",
  studentEmailVerify: "/user/register/email/code",
  adminEmailVerify:"/admin/email/code",
  getMessages: '',
  avatarUpload: '/oss/minio/putObjectTest',
  editAdminPersonalBase: '/admin/adminUser/info',
}